POST http://localhost:2525/imposters
Content-Type: application/json

{
  "port": 4548,
  "protocol": "http",
  "name": "Exercicio3",
  "stubs": [
    {
      "responses": [
        {
          "is": {
            "statusCode": 200,
            "headers": { "Content-Type": "application/json" },
            "body": {
              "brand": "Toyota",
              "results": [
                {
                  "id": 1,
                  "modelo": "Corolla",
                  "preco": 25000
                }
              ]
            }
          }
        }
      ],
      "predicates": [
        {
          "equals": {
            "method": "GET",
            "path": "/api/cars",
            "query": {
              "brand": "Toyota"
            }
          }
        }
      ]
    }
  ]
}

###



GET http://localhost:4547/api/cars?brand=Toyota